// This file was autogenerated by calcdeps.py
goog.addDependency("../../../src/main/javascript_source/org/jboss/search/visualization/Histogram.js", ['org.jboss.search.visualization.Histogram'], ['org.jboss.search.visualization.IntervalSelected', 'goog.array', 'goog.object', 'goog.string', 'goog.date.DateTime', 'goog.events.EventTarget', 'goog.debug.Logger']);
goog.addDependency("../../../src/main/javascript_source/org/jboss/search/visualization/HistogramEventType.js", ['org.jboss.search.visualization.HistogramEventType'], ['goog.events']);
goog.addDependency("../../../src/main/javascript_source/org/jboss/search/visualization/IntervalSelected.js", ['org.jboss.search.visualization.IntervalSelected'], ['org.jboss.search.visualization.HistogramEventType', 'goog.events.Event']);
