// This file was autogenerated by calcdeps.py
goog.addDependency("../../../src/main/javascript_source/org/jboss/search/visualization/Histogram.js", ['org.jboss.search.visualization.Histogram'], ['goog.array', 'goog.object', 'goog.string', 'goog.Disposable']);
