// This file was autogenerated by calcdeps.py
goog.addDependency("../../../src/main/javascript_source/org/jboss/search/list/project/Project.js", ['org.jboss.search.list.project.Project'], ['goog.object', 'goog.array', 'goog.async.Deferred']);
