// This file was autogenerated by calcdeps.py
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/util/dateTime.js", ['org.jboss.core.util.dateTime'], ['org.jboss.core.service.Locator', 'goog.string', 'goog.date.DateTime', 'goog.i18n.DateTimeFormat']);
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/util/ImageLoader.js", ['org.jboss.core.util.ImageLoader'], []);
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/util/ImageLoaderNet.js", ['org.jboss.core.util.ImageLoaderNet'], ['org.jboss.core.util.ImageLoader', 'goog.events.EventTarget', 'goog.net.ImageLoader']);
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/util/ImageLoaderNoop.js", ['org.jboss.core.util.ImageLoaderNoop'], ['org.jboss.core.util.ImageLoader']);
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/service/Locator.js", ['org.jboss.core.service.Locator'], []);
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/service/LookUp.js", ['org.jboss.core.service.LookUp'], ['goog.History', 'goog.net.XhrManager', 'goog.i18n.DateTimeFormat', 'org.jboss.core.util.ImageLoader']);
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/service/LookUpImpl.js", ['org.jboss.core.service.LookUpImpl'], ['org.jboss.core.Variables', 'org.jboss.core.service.LookUp', 'goog.History', 'goog.net.XhrManager', 'goog.i18n.DateTimeFormat', 'org.jboss.core.util.ImageLoader', 'org.jboss.core.util.ImageLoaderNoop']);
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/Variables.js", ['org.jboss.core.Variables'], []);
goog.addDependency("../../../core/src/test/javascript/org/jboss/core/util/dateTime_test.js", [], ['org.jboss.core.service.Locator', 'org.jboss.core.service.LookUpImpl', 'org.jboss.core.Variables', 'org.jboss.core.util.dateTime', 'goog.date', 'goog.date.DateTime', 'goog.i18n.DateTimeFormat', 'goog.testing.jsunit']);
