// This file was autogenerated by calcdeps.py
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/service/Locator.js", ['org.jboss.core.service.Locator'], []);
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/service/Locator_test.js", ['org.jboss.core.service.LocatorTest'], ['org.jboss.core.service.Locator', 'org.jboss.core.service.LookUpImpl', 'goog.string', 'goog.testing.jsunit']);
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/service/LookUp.js", ['org.jboss.core.service.LookUp'], ['goog.History', 'goog.net.XhrManager', 'org.jboss.core.util.ImageLoader']);
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/service/LookUpImpl.js", ['org.jboss.core.service.LookUpImpl'], ['org.jboss.core.service.LookUp', 'goog.History', 'goog.net.XhrManager', 'org.jboss.core.util.ImageLoader', 'org.jboss.core.util.ImageLoaderNoop']);
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/util/ImageLoader.js", ['org.jboss.core.util.ImageLoader'], []);
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/util/ImageLoaderNet.js", ['org.jboss.core.util.ImageLoaderNet'], ['org.jboss.core.util.ImageLoader', 'goog.events.EventTarget', 'goog.net.ImageLoader']);
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/util/ImageLoaderNoop.js", ['org.jboss.core.util.ImageLoaderNoop'], ['org.jboss.core.util.ImageLoader']);
