// This file was autogenerated by calcdeps.py
goog.addDependency("../../../searchPage/src/main/javascript/org/jboss/search/list/Project.js", ['org.jboss.search.list.Project'], ['goog.array', 'goog.async.Deferred', 'goog.object', 'goog.string']);
goog.addDependency("../../../searchPage/src/main/javascript/org/jboss/search/list/Type.js", ['org.jboss.search.list.Type'], ['goog.array', 'goog.async.Deferred', 'goog.debug.Logger', 'goog.object', 'goog.string']);
