// This file was autogenerated by calcdeps.py
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/visualization/Histogram.js", ['org.jboss.core.visualization.Histogram'], ['org.jboss.core.visualization.IntervalSelected', 'goog.array', 'goog.object', 'goog.string', 'goog.date.DateTime', 'goog.events.EventTarget', 'goog.debug.Logger']);
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/visualization/HistogramEventType.js", ['org.jboss.core.visualization.HistogramEventType'], ['goog.events']);
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/visualization/IntervalSelected.js", ['org.jboss.core.visualization.IntervalSelected'], ['org.jboss.core.visualization.HistogramEventType', 'goog.date.DateTime', 'goog.events.Event']);
