// This file was autogenerated by calcdeps.py
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/visualization/Histogram.js", ['org.jboss.core.visualization.Histogram'], ['goog.array', 'goog.date.DateTime', 'goog.debug.Logger', 'goog.events.EventTarget', 'goog.object', 'goog.string', 'org.jboss.core.visualization.IntervalSelected']);
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/visualization/HistogramEventType.js", ['org.jboss.core.visualization.HistogramEventType'], ['goog.events']);
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/visualization/IntervalSelected.js", ['org.jboss.core.visualization.IntervalSelected'], ['goog.date.DateTime', 'goog.events.Event', 'org.jboss.core.visualization.HistogramEventType']);
