// This file was autogenerated by calcdeps.py
goog.addDependency("../../../core/src/main/javascript/org/jboss/core/service/query/SimpleTimeCache.js", ['org.jboss.core.service.query.SimpleTimeCache'], ['goog.Disposable', 'goog.Timer', 'goog.array', 'goog.events', 'goog.object']);
