// This file was autogenerated by calcdeps.py
goog.addDependency("../../../searchPage/src/main/javascript/org/jboss/search/list/project/Project.js", ['org.jboss.search.list.project.Project'], ['goog.array', 'goog.async.Deferred', 'goog.object', 'goog.string']);
